"""Reproduce the actual archive displayed in manuscript Figure 2 (seed 10)."""
from pathlib import Path
import numpy as np
import creoh_scheduling as S


def main():
    seed=10
    inst=S.ScheduleGenerator().generate(seed)
    train=np.concatenate([S.EndpointBuilder().build(inst,seed),
                          S.LatinHypercubeBuilder().build(inst,seed)])
    pool=S.CandidatePool(120).grow(inst,train,S.StressBuilder().build(inst,seed),seed)
    selected,archive=S.CREoHMethod(0.7).select(pool)
    nominal,_=S.DeterministicMethod().select(pool)
    points=sorted(set((f.f1,f.f2) for f,_ in archive.items))
    front=[];best=float('inf')
    for x,y in points:
        if y<best:
            front.append((x,y));best=y
    def point(c):return (float(c.train.mean()),S.OWARisk(0.7)(c.train))
    def coords(points):return ' '.join(f'({x:.8f},{y:.8f})' for x,y in points)
    target=Path(__file__).resolve().parent/'interface_example.tex'
    target.write_text('% Generated by generate_interface_example.py; actual costs, seed 10.\n'
      +r'\addplot[cGreen, very thick, mark=*, mark options={fill=cGreen}] coordinates {'+coords(front)+'};\n'
      +r'\addlegendentry{C-R-EoH frontier}'+'\n'
      +r'\addplot[only marks, mark=square*, mark options={fill=cOrange}, cOrange] coordinates {'+coords([point(nominal)])+'};\n'
      +r'\addlegendentry{Nominal selection}'+'\n'
      +r'\addplot[only marks, mark=diamond*, cBlue, mark size=3pt] coordinates {'+coords([point(selected)])+'};\n'
      +r'\addlegendentry{Selected ($\theta=0.7$)}'+'\n')
    print(f'Wrote {target.name}: seed {seed}, {len(front)} projected frontier points')


if __name__=='__main__':main()
