"""Common macro writer for the logged local-model pilots (Qwen-7B, Qwen-27B).

The number formats are those of ``make_macros.py`` for the Claude pilot, so that
the three pilots are typeset identically: percentages and indices with one
decimal, hypervolume with two, p-values via ``make_macros._p`` and Cliff's
delta with two signed decimals.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

from make_macros import _p

HERE = Path(__file__).resolve().parent


class PilotMacroWriter:
    """Emit the manuscript macros of one logged local-model pilot."""

    prefix: str = ""
    data_subdir: str = ""
    out_name: str = ""
    generator: str = ""

    SELECTORS = (("LLM pool + nominal evaluator", "Nom"),
                 ("LLM pool + fuzzy MO evaluator (C-R-EoH)", "Fuzzy"))
    METRICS = (("f1", "Cost"), ("f2", "Risk"), ("f3", "Dispersion"),
               ("p95", "Tail"), ("hv", "Hv"), ("ood", "Ood"))

    def __init__(self, root: Path = HERE) -> None:
        self.root = root
        path = root / "data" / self.data_subdir / "llm_pilot_metadata.json"
        self.meta = json.loads(path.read_text())

    @staticmethod
    def _math(text: str) -> str:
        return "\\ensuremath{" + text + "}"

    @classmethod
    def _pct(cls, value: float) -> str:
        return cls._math(f"{value:.1f}\\%")

    @staticmethod
    def _count(value: float) -> str:
        return f"{value:.1f}".rstrip("0").rstrip(".")

    def _p_value(self) -> str:
        stats = {row[0]: row for row in self.meta["stats"]}
        probability = stats["p95"][2]
        if not math.isfinite(probability) or not 0 < probability <= 1:
            raise ValueError("Non-reportable p-value")
        return self._math(_p(probability).strip("$"))

    def values(self) -> dict[str, str]:
        m = self.meta
        stats = {row[0]: row for row in m["stats"]}
        status = m["execution_status"]
        out = {
            "Programs": str(m["programs_generated"]),
            "Admitted": str(m["programs_admitted"]),
            "Executions": str(m["executions"]),
            "Seeds": str(m["seeds"]),
            "Usable": self._count(m["mean_pool_size"]),
            "Successful": str(status.get("ok", 0)),
            "Errors": str(status.get("error", 0)),
            "Invalid": str(status.get("infeasible", 0)),
            "Feas": self._pct(100 * m["feasible_before_repair_rate"]),
            "Repair": self._pct(100 * m["repair_rate"]),
            "TailReduction": self._pct(m["tail_reduction_pct"]),
            "TailP": self._p_value(),
            "TailD": self._math(f"{stats['p95'][3]:+.2f}"),
        }
        for label, sel in self.SELECTORS:
            for metric, suffix in self.METRICS:
                mean, ci = m["summary"][label][metric]
                precision = 2 if metric == "hv" else 1
                out[sel + suffix] = self._math(f"{mean:.{precision}f}")
                out[sel + suffix + "CI"] = self._math(
                    f"{mean:.{precision}f}\\pm{ci:.{precision}f}")
        return {self.prefix + k: v for k, v in out.items()}

    def write(self) -> Path:
        lines = [f"% Auto-generated by {self.generator}; do not edit."]
        lines += ["\\newcommand{\\" + k + "}{" + v + "}"
                  for k, v in self.values().items()]
        target = self.root / self.out_name
        target.write_text("\n".join(lines) + "\n")
        return target


class QwenSmallMacros(PilotMacroWriter):
    """Qwen-7B pilot (Qwen2.5-Coder 7B, Q4_K_M, released under ollama_pilot/)."""
    prefix, data_subdir = "Qwen", "ollama_pilot"
    out_name, generator = "ollama_macros.tex", "make_ollama_macros.py"


class QwenLargeMacros(PilotMacroWriter):
    """Qwen-27B pilot (local tag qwen3.8:27b-mlx, released under qwen27_pilot/)."""
    prefix, data_subdir = "QwenLarge", "qwen27_pilot"
    out_name, generator = "qwen27_macros.tex", "make_qwen27_macros.py"
